platform :ios, '10.0'
use_frameworks!

target 'BitmojiSampleApp' do
    workspace 'BitmojiSampleApp.xcworkspace'
    project 'BitmojiSampleApp.xcodeproj'
    pod 'SnapSDK', '1.1.4', :subspecs => ['SCSDKLoginKit', 'SCSDKBitmojiKit']
end

